[tool.poetry]
name = "learnrob3"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyinfra = "^2.8"
matplotlib = "^3.8.2"
numpy = "^1.26.3"
ipynb = "^0.5.1"
ipykernel = "^6.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
