[tool.poetry]
name = "learnrob3"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyinfra = "^2.8"
ujson = "^5.9.0"
isort = "^5.13.2"
bokeh = "^3.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
