# Mosquitto configuration for simulation

# Authentication
user mosquitto
password_file /mosquitto/config/passwd
allow_anonymous false

# MQTT listener
listener 1883
protocol mqtt

# Websockets listener
listener 9001
protocol websockets

# Persistence
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type all
